### ISSUE TITLE
无法播放问题

### ISSUE THREAD

**Issue by YeYuanYuan** [Windsander/Android-UltimateGPUImage#1]
1 录制成功后调用系统的默认播放器播放视频
2 但是用第三方的“万能播放器能播放”

2017 03 29 16：19

**Comment by Windsander** [comment]
因为采用的是Android API 18 后，系统提供的MediaCodec完成的视频录制，所以：
必须高于18，否则无法使用录制功能。
针对部分手机如：Vivo Vivo Y51A (Android 5.0.2, API 21)。用系统的播发器无法播放录制的视频。
目前还不能明确原因，可能的情况是关键帧（同步帧）间隔的配置在部分AOSP系统上不兼容导致的。
目前AsyncFrame（B）取得是5帧一个（f/p）
感谢您指出错误，后续会提供自定义的录制参数设定方法，并尝试解决问题。
