### ISSUE TITLE
怎么使用多个滤镜处理视频数据

### ISSUE THREAD

**Issue by Moluth** [Windsander/Android-UltimateGPUImage#11]
目前只能用1个滤镜吗？有没有可能支持多个滤镜

**Comment by Windsander** [comment]
小伙子，当然可以多个滤镜呀。你看filter文件下的multiGroupFilter就对了。需要你建立个类，并把你想用的滤镜添加到类里去加载呢。最近都在做优化，后续优化完了，做个详细的wiki。
