### ISSUE TITLE
640*480,预览页面被拉长

### ISSUE THREAD

**Issue by YeYuanYuan** [Windsander/Android-UltimateGPUImage#2]
我仔细对比的，发现预览的时候所看的界面显示的都被拉长稍微一定。跟正常的手机的拍摄预览不同。
宽高比修改后预览不流畅，是否可以对宽高的修改

**Comment by Windsander** [comment]
目前暂时还不能修改款高。下一个版本就可以做音视频初始属性的自定义了。
