### ISSUE TITLE
Recorded video is looking a stretched

### ISSUE THREAD

**Issue by achinverma** [Windsander/Android-UltimateGPUImage#29]
@Windsander , The recorded video is looking a stretched, Please see the image of the recorded video.
I have downloaded your demo from github and after running your demo in my moto g5 plus device, I am facing this issue.
![44643358-dd4db200-a9ed-11e8-9f60-096f85668122](https://user-images.githubusercontent.com/2811593/44787994-70394880-abb6-11e8-99ad-569f29a8adcb.png)

**Comment by Windsander** [comment]
avconfig is wrong, you need to reset it by this method, if you want to do some self define work:
```java
    // u can use this method to set ur own config rather than default one.(this is not necessary)
    mRecordManager.setAVConfig(videoConfig, audioConfig);
```
vedioConfig & audioConfig will give to RecordManager's params:
```java
    private OutputConfig.VideoOutputConfig mVideoConfig;
    private OutputConfig.AudioOutputConfig mAudioConfig;
```
and your problem is caused by wrong config.
you need to reset it's videoHeight & videoWidth params
