### ISSUE TITLE
部分手机预览方向和输出视频方向差180°

### ISSUE THREAD

**Issue by zhourihu5** [Windsander/Android-UltimateGPUImage#3]
发现的手机有 魅蓝 手机

**Comment by Windsander** [comment]
这个原因是因为部分手机的自定制系统，在相机实现上主动的加了旋转代码到源码级别（原生Android系统，相机图片会180度旋转，本项目为了避免这种情况又加了一次180）。因此相当于旋转了3次180度，导致统一处理失效了。

**Comment by zhourihu5** [comment]
这个项目就没有这个问题，具体关键处理差异我也不清楚，你研究明白了可以分享一下，链接：https://github.com/zhourihu5/BVideo

**Comment by Windsander** [comment]
哦哦～好的👌～
