### ISSUE TITLE
尝试用了 vedioView 去播放录制的视频，也无法播放。  第三方的播放器才能播放。好奇原因

### ISSUE THREAD

**Issue by YeYuanYuan** [Windsander/Android-UltimateGPUImage#5]

**Comment by Windsander** [comment]
这个我感觉是因为视频录制关键帧设置导致的。我在项目里目前还没有暴露设置关键同步帧（B）间隔的方法。目前，同步帧（主要作用是保证音视频同步）的间隔为5ms。对于原生播放器来说，可能有些频繁了。
后续版本会暴露所有的关键配置方法。现在测试的话，可以在core_config目录下的配置文件中找到。

**Comment by Windsander** [comment]
补充说明：
需要修改的配置为：
public static final int IFRAME_INTERVAL = 1; 
目前为1帧一个，的确有点短了。你可以先修改它，看是否满足需求，建议按照 5、10、20修改
