### ISSUE TITLE
快速的点击播放暂停切换会崩溃

### ISSUE THREAD

**Issue by YeYuanYuan** [Windsander/Android-UltimateGPUImage#6]

**Comment by Windsander** [comment]
这个问题主要是因为录制流启动是顺序的，虽然我加了队列管理录制的流程，但是如果过快的调用方法的话，仍然会导致start、stop过快的调用，使得系统资源索求与释放过快发生。导致崩溃。所以崩溃的原因一般就会报 cant stop exception，就是因为资源分配过程中，无法立即释放（总是有个过程的，而这个过程里，底层驱动器会去请求较多的资源）。

**Comment by Windsander** [comment]
毕竟，音视频算是手机系统里消耗最多的功能了。
